version: '3.4'

services:

    db:
        image: timescale/timescaledb:latest-pg12
        environment:
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        volumes: 
            # - ./db/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
            # - ./db:/var/lib/postgresql/data/postgresql.conf
            - ./data:/var/lib/postgresql/data
        ports:
            - 54320:5432
    app:
        build: ./app
        environment:
            - DEBUG=${DEBUG}
            - SECRET_KEY=${SECRET_KEY}
            - DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}
        volumes:
            - ./app:/app
        ports:
            - "8000:8000"
        depends_on:
            - db
        command: python manage.py runserver 0.0.0.0:8000


    # pgadmin:
    
    # schemaspy:

    # grafana: 
