# Generated by Django 3.1.2 on 2020-10-07 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transaction_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alipay_id', models.CharField(max_length=100, unique=True)),
                ('creation_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('origin', models.IntegerField(choices=[(1, 'Taobao'), (2, 'Alipay'), (3, 'Other')])),
                ('type', models.IntegerField(choices=[(1, 'Alipay Protected'), (2, 'Booking'), (3, 'Instant')])),
                ('sign', models.IntegerField(choices=[(1, 'Expenditure'), (2, 'Income')])),
                ('state', models.IntegerField(choices=[(1, 'Awaiting Reception Confirmation'), (2, 'Closed'), (3, 'Paid'), (4, 'Transfer Failed'), (5, 'Added Value'), (6, 'Failure'), (7, 'Unfreezed'), (8, 'Paid By Others'), (9, 'Freezed'), (10, 'Awaiting Payment'), (11, 'Refunded'), (12, 'Transaction Successful'), (13, 'Transaction Closed')])),
                ('funds_state', models.IntegerField(choices=[(1, 'Awaiting Expenditure'), (2, 'Paid'), (3, 'Funds Transfer'), (4, 'Frozen'), (5, 'Received'), (6, 'Unfrozen')])),
                ('order_num', models.CharField(max_length=100)),
                ('last_modified_date', models.DateTimeField()),
                ('payment_date', models.DateTimeField()),
                ('counterpart', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
