# Generated by Django 3.1.2 on 2020-10-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201007_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawtransaction',
            name='last_modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawtransaction',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
