# Generated by Django 3.1.2 on 2020-10-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201007_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawtransaction',
            name='funds_state',
            field=models.IntegerField(choices=[(1, 'Awaiting Expenditure'), (2, 'Paid'), (3, 'Funds Transfer'), (4, 'Frozen'), (5, 'Received'), (6, 'Unfrozen')], null=True),
        ),
        migrations.AlterField(
            model_name='rawtransaction',
            name='sign',
            field=models.IntegerField(choices=[(1, 'Expenditure'), (2, 'Income')], null=True),
        ),
    ]
