# Generated by Django 3.1.2 on 2020-10-09 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201009_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawtransaction',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='rawtransaction',
            name='service_fee',
        ),
        migrations.AddField(
            model_name='order',
            name='counterpart',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.counterpart'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='user_full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='rawtransaction',
            name='counterpart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.counterpart'),
        ),
    ]
