# Generated by Django 3.1.2 on 2020-10-10 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201009_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='counterpart',
        ),
        migrations.RemoveField(
            model_name='rawtransaction',
            name='counterpart',
        ),
        migrations.AddField(
            model_name='account',
            name='kind',
            field=models.IntegerField(choices=[(1, 'Personal'), (2, 'Enterprise')], default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='other_party_account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='order_other_party_accounts', to='core.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawtransaction',
            name='other_party_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_other_party_accounts', to='core.account'),
        ),
        migrations.AlterField(
            model_name='rawtransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_accounts', to='core.account'),
        ),
        migrations.DeleteModel(
            name='Counterpart',
        ),
    ]
