# Generated by Django 3.1.2 on 2020-10-11 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201010_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='order_account', to='core.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rawtransaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_accounts', to='core.account'),
        ),
    ]
