# Generated by Django 3.1.2 on 2020-10-11 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201011_0313'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RawTransaction',
            new_name='Transaction',
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='Operation',
        ),
        migrations.RenameField(
            model_name='Transaction',
            old_name='order',
            new_name='operation'
        ),
    ]
