# Generated by Django 3.1.2 on 2020-10-17 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_account_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transfer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.transfer'),
        ),
    ]
